### ISSUE TITLE
`emit_region` not recognized

### ISSUE THREAD

**Issue by fungb** [ilebedev/py_macro_processor#1]
```
Traceback (most recent call last):
  File "./logic_library/py_macro_processor/pymacro.py", line 55, in <module>
    main(sys.argv[1], args)
  File "./logic_library/py_macro_processor/pymacro.py", line 40, in main
    py_results = [( eval(s[1].strip(), file_scope) if s[0] else do_exec(s[1].strip()) ) for s in py_segments]
  File "<string>", line 1, in <module>
TypeError: axi_ports_list() got an unexpected keyword argument 'emit_region'
Makefile:23: recipe for target 'FPGAServices.v' failed
make: *** [FPGAServices.v] Error 1
```

**Comment by ilebedev** [comment]
(see slack) :]
